config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :lessons
  resources :users, only: :show

  resources :institutions
  resources :institutions do
      resources :lessons
  end

root 'lessons#index'
  post 'signup' => 'devise/registrations#create', :as => :custom_user_registration
  get 'institutions/index'

  get 'institutions/show'

  get 'institutions/new'

  get 'institutions/create'

  get 'institutions/edit'

  get 'institutions/update'

  get 'institutions/destroy'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    
      user ||= User.new 

    # Handle the case when guest user (not logged in)

      if user.role == 'admin'
        can :manage, :all
      elsif
        user.role == 'owner'
        can :read, :all
        can :create, @lesson
        can :create, Lesson
        can :update, Lesson do |lesson|
          (lesson && lesson.owner == user.id)
          end
        can :destroy, Lesson do |lesson|
          (lesson && lesson.owner == user.id)
          end
      else
          can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/institution.rb
class Institution < ActiveRecord::Base

	has_many :lessons
	validates :inst_name, presence: true, length: {minimum: 5} 
	validates :inst_id, presence: true, length: {minimum: 7, message: "The Institution Code is too short" } 
	validates_inclusion_of :inst_zip, in: 10000..11999, message: "is not a valid zipcode"
	validates_length_of :inst_phone, in: 7..16, allow_blank: true, message: "Please enter a valid phone number"
	validates :inst_add1, presence: true, length: {minimum: 5, message: "Please enter a valid address"}
	validates :inst_state, presence: true
	validates_inclusion_of :inst_state, in: %w(AK	Alaska	KY	Kentucky	NY	New York
AL	Alabama	LA	Louisiana	OH	Ohio
AR	Arkansas	MA	Massachusetts	OK	Oklahoma
AZ	Arizona	MD	Maryland	OR	Oregon
CA	California	ME	Maine	PA	Pennsylvania
CO	Colorado	MI	Michigan	RI	Rhode Island
CT	Connecticut	MN	Minnesota	SC	South Carolina
DC	District of Columbia	MO	Missouri	SD	South Dakota
DE	Delaware	MS	Mississippi	TN	Tennessee
FL	Florida	MT	Montana	TX	Texas
GA	Georgia	NC	North Carolina	UT	Utah
HI	Hawaii	ND	North Dakota	VA	Virginia
IA	Iowa	NE	Nebraska	VT	Vermont
ID	Idaho	NH	New Hampshire	WA	Washington
IL	Illinois	NJ	New Jersey	WI	Wisconsin
IN	Indiana	NM	New Mexico	WV	West Virginia
KS	Kansas	NV	Nevada	WY	Wyoming), message: "%{value} is not an existing state code in USA"

	geocoded_by :address
	after_validation :geocode 
	# , :if => :address_changed? 


	def address
	  [inst_add1, inst_add2, inst_city, inst_state, inst_zip].compact.join(", ")
	end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	belongs_to :institution
	belongs_to :user
	validates :name, presence: true, length: { minimum: 5}
	validates :institution_id, presence: true, length: { minimum: 7}

	scope :my_lessons, -> (user_id) { where(owner: user_id) }
	
	def self.search_for(query)
	    where('name LIKE :query OR description LIKE :query OR category LIKE :query', query: "%#{query}%")
  	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :lessons
  validates :email, presence: true, length: { minimum: 5}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   # ROLES = %w[admin owner parent]
 
# def roles=(roles)
# 	self.roles_mask = (roles & ROLES).map {|r| 2**ROLES.index(r)}.sum
# end

# def roles
# 	ROLES.reject {|r| ((roles_mask || 0) & 2**ROLES.index(r)).zero?}
# end
#   def role?(role)
# 	  roles.include? role.to_s	
#   end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Catch all CanCan errors and alert the user of the exception
  rescue_from CanCan::AccessDenied do | exception |
    redirect_to root_url, alert: exception.message
  end

  before_filter do
  resource = controller_name.singularize.to_sym
  method = "#{resource}_params"
  params[resource] &&= send(method) if respond_to?(method, true)
end
  
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController

  def index
    @institutions = Institution.all
  end

  def show
    @institution = Institution.find(params[:id])
  end

  def new
    @institution = Institution.new
  end

  def create
    @institution = Institution.new(institution_params)
    if 
      @institution.save
      redirect_to @institution
    else
      render 'new'
    end
  end

  def edit
    @institution = Institution.find(params[:id])
  end

  def update
    @institution = Institution.find(params[:id])
    if 
      @institution.update(institution_params)
      redirect_to @institution
    else
      render 'edit'
    end
  end

  def destroy
    @institution = Institution.find(params[:id])
    @institution.destroy
    redirect_to institutions_path
  end

  private
  def institution_params
    params.require(:institution).permit(:inst_name, :inst_id, :inst_add1, :inst_add2, :inst_city, :inst_state, :inst_zip, :inst_url, :inst_phone)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

load_and_authorize_resource

before_action :authenticate_user!, only: [:new, :create, :update, :delete]


  def index
    
    @lessons = if params[:q] && params[:my_lessons]
      Lesson.my_lessons(current_user.id).search_for(params[:q])
    elsif params[:q]
      Lesson.search_for(params[:q])
    elsif params[:my_lesson]
      Lesson.my_lessons(current_user.id)
    else
      Lesson.all
    end

    # @lessons = params[:q] ? Lesson.search_for(params[:q]) : Lesson.all
  end

  def show
    @lesson = Lesson.find(params[:id])
    @location = Institution.find_by_inst_id(@lesson.institution_id)
  end

  def new
    if can? :create, @lesson
      @lesson = Lesson.new
    end
  end

  def create
    @lesson = Lesson.new(lesson_params)
    @lesson.owner = current_user.id
    if 
      @lesson.save
      redirect_to @lesson
    else
      render 'new'
    end
  end

  def edit
  
    if can? :update, @lesson
      @lesson = Lesson.find(params[:id])
    end
  end

  def update
    @lesson = Lesson.find(params[:id])
    if 
      @lesson.update(lesson_params)
      redirect_to @lesson
    else
      render 'edit'
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    redirect_to lessons_path
  end

  

private
def lesson_params
params.require(:lesson).permit(:name, :description, :min_age, :max_age, :weekday, :category, :institution_id)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	load_and_authorize_resource
	

  def index
  @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if 
      @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if 
      @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :encrypted_password, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/institutions/_form.html.erb
<%= form_for(@institution) do |f| %>
	<% if @institution.errors.any? %>
		<div class="error-explanation">
		 <h2> <%= pluralize(@institution.errors.count, "error")%> prevented this institution from being saved </h2>

		 <ul>
			 <% @institution.errors.full_messages.each do |msg| %>
			   <li><%= msg %></li>
			 <%end%>
		 </ul>
		</div>
	<%end%>

	<p>
     	<%= f.label "Institution Name" %><br>
	  	<%= f.text_field :inst_name %><br>
    </p>

    <p>
        <%= f.label "Institution Code" %><br>
        <%= f.text_field :inst_id %><br>
    </p>

    <p>
     	<%= f.label "Address Line 1"%><br>
	  	<%= f.text_field :inst_add1  %><br>
    </p>

     <p>
     	<%= f.label "Address Line 2" %><br>
	  	<%= f.text_field :inst_add2 %><br>
    </p>

     <p>
     	<%= f.label "City" %><br>
	  	<%= f.text_field :inst_city %><br>
    </p>

     <p>
     	<%= f.label "State" %><br>
	  	<%= f.text_field :inst_state%><br>
    </p>

    <p>
     	<%= f.label "Zip" %><br>
	  	<%= f.text_field :inst_zip%><br>
    </p>

    <p>
     	<%= f.label "Phone" %><br>
	  	<%= f.text_field :inst_phone%><br>
    </p>

	<p>
     	<%= f.label "Website" %><br>
	  	<%= f.text_field :inst_url%><br>
    </p>

<%= f.submit %>
<%end%>

<h4><%= link_to "Back", institutions_path %></h4>

app/views/institutions/create.html.erb
<h1>Institutions#create</h1>
<p>Find me in app/views/institutions/create.html.erb</p>

app/views/institutions/destroy.html.erb
<h1>Institutions#destroy</h1>
<p>Find me in app/views/institutions/destroy.html.erb</p>

app/views/institutions/edit.html.erb
<h1>Edit an Institution</h1>

<%= render 'form' %>

app/views/institutions/index.html.erb
<h1>List of All Institutions</h1>

<table class="table table-hover">
  <thead>
    <tr>
  	  <th>S.No.</th>
      <th>Institution Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
    </tr>
  </thead>

<% i=1 %>
<% @institutions.each do |biz| %>
  <tbody>
    <tr>
      <td><%= i %></td>	
      <td><%= biz.inst_name %></td>
      <td><%= biz.inst_add1%>, <%= biz.inst_city%>, <%= biz.inst_state%>, <%= biz.inst_zip%></td>
      <td><%= biz.inst_phone %></td>
      <td><%= biz.inst_url %></td>
      
      
      <td><%= link_to 'Show', institution_path(biz) %></td>
      <% if can? :update, @institution%>
      <td><%= link_to 'Edit', edit_institution_path(biz) %></td>
      <%end%>
      <% if can? :destroy, @institution%>
      <td><%= link_to 'Delete', institution_path(biz), method: :delete, data: {confirm: 'Are you sure ?'} %></td>
      <%end%>
    </tr>
  </tbody>
<%i +=1 %>
<% end %>
</table>
</br>

<h3><%= link_to "Add a New Institution", new_institution_path %></h3>

<h3><%= link_to 'Home', root_path%></h3>

app/views/institutions/new.html.erb
<h1>Add a New Institution</h1>

<%= render 'form' %>

app/views/institutions/show.html.erb
<h1>Institutions Details</h1>

<p>
<strong> Institution Name: </strong>
<%= @institution.inst_name %>
</p>

<p>
<strong> Address: </strong>
<%= @institution.inst_add1 %>, <%= @institution.inst_city %>, <%= @institution.inst_state %>, <%= @institution.inst_zip %>
</p>

<p>
<strong> Phone: </strong>
<%= @institution.inst_phone %>
</p>

<p>
<strong> Website: </strong>
<%= link_to @institution.inst_url, @institution.inst_url %>
</p>

<h4><%= link_to "Back", institutions_path %></h4>

app/views/institutions/update.html.erb
<h1>Institutions#update</h1>
<p>Find me in app/views/institutions/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <title>LessonsApp</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>

  <%= yield %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="http://code.jquery.com/jquery.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
</body>
</html>

app/views/lessons/_form.html.erb
<%= form_for(@lesson) do |f| %>
	<% if @lesson.errors.any? %>
		<div class="error-explanation">
		 <h2> <%= pluralize(@lesson.errors.count, "error")%> prevented this class from being saved </h2>

		 <ul>
			 <% @lesson.errors.full_messages.each do |msg| %>
			   <li><%= msg %></li>
			 <%end%>
		 </ul>
		</div>
	<%end%>

	<p>
     	<%= f.label :name %><br>
	  	<%= f.text_field :name %><br>
    </p>

    <p>
     	<%= f.label :description %><br>
	  	<%= f.text_field :description %><br>
    </p>

	<p>
     	<%= f.label "Category" %><br>
	  	<%= f.text_field :category %><br>
    </p>

    <p>
     	<%= f.label "Institution Code" %><br>
	  	<%= f.text_field :institution_id %><br>
    </p>

     <p>
     	<%= f.label :weekday %><br>
	  	<%= f.text_field :weekday %><br>
    </p>

     <p>
     	<%= f.label "Minimum Age" %><br>
	  	<%= f.text_field :min_age %><br>
    </p>

     <p>
     	<%= f.label "Maximum Age" %><br>
	  	<%= f.text_field :max_age %><br>
    </p>

    

<%= f.submit %>
<%end%>


<h4><%= link_to 'Back', lessons_path%></h4>

app/views/lessons/create.html.erb
<h1>Lessons#create</h1>
<p>Find me in app/views/lessons/create.html.erb</p>

app/views/lessons/destroy.html.erb
<h1>Lessons#destroy</h1>
<p>Find me in app/views/lessons/destroy.html.erb</p>

app/views/lessons/edit.html.erb
<h1>Update a Class</h1>

<%= render 'form' %>

app/views/lessons/index.html.erb
<h1>Welcome to Class Act</h1>

<%= form_tag '/', method: :get do %>
  <%= search_field_tag :q, params[:q] %>
  <%= submit_tag "Search" %>
  <br/>
  <%= check_box_tag 'my_lessons' %>
  <%= submit_tag "My class listings" %>
<% end %>

<br/>

<table class="table table-hover">
  <thead>
    <tr>
  	  <th>S.No.</th>
      <th>Class Name</th>
      <th>Description</th>
      <th>Weekday</th>
      <th>Ages</th>
    </tr>
  </thead>

<% i=1 %>
<% @lessons.each do |lesson| %>
  <tbody>
    <tr>
      <td><%= i %></td>	
      <td><%= lesson.name %></td>
      <td><%= lesson.description %></td>
      <td><%= lesson.weekday %></td>
      <td><%= lesson.min_age %> to </td>
      <td><%= lesson.max_age %></td>
      <td><%= link_to 'More details', lesson_path(lesson) %></td>
      
      <% if can? :update, @lesson%>
      <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
      <%end%>

      <% if can? :destroy, @lesson%>
        <td><%= link_to 'Delete', lesson_path(lesson), method: :delete, data: {confirm: 'Are you sure ?'} %></td>
      <%end%>
     </tr>
  </tbody>
<%i +=1 %>
<% end %>
</table>

<% if (user_signed_in?) && (can? :create, @lesson) %>
  
  <h3><%= link_to "Add a New Class", new_lesson_path %></h3>
<% end %>

<% if (user_signed_in?) && (can? :manage, @user) %>
  
  <h3><%= link_to "See list of Institutions", institutions_path %></h3>
   <h3><%= link_to "See list of Users", users_path %></h3>
<% end %>

<h3><%= link_to "Home", lessons_path %></h3>

app/views/lessons/new.html.erb
<h1>Add a New Class</h1>

<%= render 'form' %>

app/views/lessons/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<h3 id="classDetails"> Details of selected class: </h3>


<div class="class-details">

<div id="classImage">
  <%= image_tag @lesson.image %>
</div>

<p>
<strong> Class Name: </strong>
  <%= @lesson.name %>
</p>

<p>
<strong> Description: </strong>
  <%= @lesson.description %>
</p>

<p>
<strong> Weekday: </strong>
  <%= @lesson.weekday %>
</p>

<p>
<strong> Ages: </strong>
  <%= @lesson.min_age%> to <%= @lesson.max_age%> years
</p>

</div>



<%= link_to 'Back', lessons_path %>
<% if can? :update, @lesson %>
  <%= link_to 'Edit', edit_lesson_path(@lesson) %>
<%end%>

<% if can? :destroy, @lesson %>
<%= link_to 'Delete', lesson_path(@lesson), method: :delete, data: {confirm: 'Are you sure ?'} %>
<%end%>


<h3 id="classLoc"> Class Location: </h3>

<div class="location-details">

<p>
<strong> Institution: </strong>
<%= @location.inst_name %>
</p>

<p>
<strong> Address: </strong>
<%= @location.inst_add1 %>, <%= @location.inst_city %>, <%= @location.inst_state %>, <%= @location.inst_zip %>
</p>

<p>
<strong> Phone: </strong>
<%= @location.inst_phone %>
</p>

<p>
<strong> Website: </strong>
<%= link_to @location.inst_url, @location.inst_url %>
</p>
</div>



<script>
  var latitude = <%= @location.latitude %>
  var longitude = <%= @location.longitude %>  
</script>

<div style='width: 522px;'>
  <div id="map" style='width: 512px; height: 300px;'></div>
</div>

<script type="text/javascript">	
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  	markers = handler.addMarkers([
    {
      "lat": latitude,
      "lng": longitude,
      "picture": {
        "image": "map-marker-red.png",
        "width":  36,
        "height": 36,
      },
      "infowindow": "hello!"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(16);
});
</script>


<div class="nearby-locations">
	<h3 id= "nearbyLocs">Nearby locations</h3>
<ul> 
<% for location in @location.nearbys(2) %> 
<li><%= link_to location.inst_name, location %> (<%= location.distance.round(2) %> miles)</li>
<%end%>
</ul>
</div>

app/views/lessons/update.html.erb
<h1>Update a Class</h1>
<p>Find me in app/views/lessons/update.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
		<div class="error-explanation">
		 <h2> <%= pluralize(@user.errors.count, "error")%> prevented this user from being saved </h2>

		 <ul>
			 <% @user.errors.full_messages.each do |msg| %>
			   <li><%= msg %></li>
			 <%end%>
		 </ul>
		</div>
	<%end%>

	<p>
     	<%= f.label "User Email" %><br>
	  	<%= f.text_field :email %><br>
    </p>

	<p>
     	<%= f.label "User Password" %><br>
	  	<%= f.text_field :encrypted_password %><br>
    </p>

    <p>
     	<%= f.label "Role"%><br>
	  	<%= f.text_field :role %><br>
    </p>

<%= f.submit %>
<%end%>

<h4><%= link_to "Back", users_path %></h4>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>List of Users</h1>

<br/>

<table class="table table-hover">
  <thead>
    <tr>
  	  <th>User Id</th>
      <th>User Email</th>
      <th>Role</th>
    
    </tr>
  </thead>

<% @users.each do |user| %>
  <tbody>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.email %></td>
      <td><%= user.role %></td>

     <% if can? :update, @user%>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <%end%>
      <% if can? :destroy, @user%>
        <td><%= link_to 'Delete', user_path(user), method: :delete, data: {confirm: 'Are you sure ?'} %></td>
      <%end%>
    </tr>
  </tbody>

<% end %>
</table>

<% if (user_signed_in?) && (can? :create, @user) %>
  
  <h3><%= link_to "Add a New User", new_user_path %></h3>
<% end %>

<h3><%= link_to 'Home', root_path%></h3>
<br/>
<br/>

app/views/users/new.html.erb
<h1>Add New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h3>User Details<h3>

<h3><%= link_to "Back", users_path %></h3>

<div id="users">
 
<h1>User Details</h1>

<p>
<strong> User Id: </strong>
<%= @user.id %>
</p>

<p>
<strong> User Name: </strong>
<%= @user.email %>
</p>

<p>
<strong> User Access: </strong>
<%= @user.role %>
</p>

</div>